#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

# Override what is set by the baseimage and do not set the variable. Needed for
# WebGL support.
exit 100

# vim:ft=sh:ts=4:sw=4:et:sts=4
