#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

LINE="$1"

#if echo "$LINE" | grep -q "OutOfMemoryError occurred...RESTARTING!"; then
if [ "$LINE" = "###!!! [Parent][MessageChannel] Error: (msgtype=0x150084,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv" ]
then
    exit 0
fi

# No match found.
exit 1

# vim: set ft=sh :
