#!/bin/sh
#
# When receiving SIGTERM, Firefox doesn't qui immediately and instead ask for
# confirmation.  Instead, terminate Firefox by sending the CTRL+q key presses.
#

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

xdotool key "Escape"
xdotool key "ctrl+q"

# vim:ft=sh:ts=4:sw=4:et:sts=4

