name: Docker image CI/CD
permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_IMAGE_NAME: jneisener/firefox
  PLATFORMS: linux/amd64,linux/386,linux/arm/v7,linux/arm64/v8

on:
  push:
    branches: '*'
    tags:
      - v[0-9][0-9].[0-9][0-9].[0-9]+
      - v[0-9][0-9].[0-9][0-9].[0-9]+-pre.[0-9]+
  pull_request:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-22.04

    steps:
#      - name: Free disk space
#        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
#        with:
#          tool-cache: true
#          android: true
#          dotnet: true
#          haskell: true
#          large-packages: true
#          docker-images: true
#          swap-storage: false
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: actions-ecosystem/action-get-latest-tag@b7c32daec3395a9616f88548363a42652b22d435 # v.1.6.0
        id: get-latest-tag

      - name: Prepare
        id: prep
        run: |
          # Determine the Docker container version.
          VERSION=unknown
          if [[ $GITHUB_REF =~ refs/tags/* ]]; then
            # Git tag pushed: use tag as the version.
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF =~ refs/heads/* ]]; then
            # Git commit pushed: use the commit SHA as the version.
            VERSION=$(echo ${{ steps.get-latest-tag.outputs.tag }}| cut -d- -f1)-$(printf '%(%Y%m%d%H%M%S)T\n' -1)
          elif [[ $GITHUB_REF =~ refs/pull/* ]]; then
            # Pull request: use PR number as the version.
            VERSION=pr-${{ github.event.number }}
          else
            echo "::error::Unexpected GITHUB_REF: $GITHUB_REF"
            exit 1
          fi
          # Determine the version to put in container label.
          LABEL_VERSION=${VERSION}
          if [[ $GITHUB_REF =~ refs/tags/* ]]; then
            # Do not include the starting 'v' of the version.
            LABEL_VERSION=${VERSION:1}
          fi
          # Determine the Docker container tags.
          TAGS="${{ env.DOCKER_IMAGE_NAME }}:${VERSION}"
          if [[ $GITHUB_REF =~ refs/heads/* ]]; then
            TAGS="$TAGS,${{ env.DOCKER_IMAGE_NAME }}:latest"
          fi
          TAGS="$TAGS,$(echo $TAGS | tr ',' '\n' | sed 's|^|ghcr.io/|' | tr '\n' ',')"
          # Print results.
          echo "::group::Results"
          echo "Github reference: $GITHUB_REF"
          echo "Docker container version: $VERSION"
          echo "Docker container version label: $LABEL_VERSION"
          echo "Docker container tag(s): $TAGS"
          echo "::endgroup::"
          # Export outputs.
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "label_version=${LABEL_VERSION}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          #echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v4.1.0
        with:
          platforms: arm,arm64,ppc64le,mips64,s390x

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v4.1.0

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v7.2.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.prep.outputs.tags }}
          build-args: |
            DOCKER_IMAGE_VERSION=${{ steps.prep.outputs.label_version }}
          cache-from: type=gha,scope=${{ env.DOCKER_IMAGE_NAME }}
          cache-to: type=gha,mode=max,scope=${{ env.DOCKER_IMAGE_NAME }}

      - uses: actions-ecosystem/action-push-tag@6e82caefe706f5a729e354df7443dc82f98a414f # v1.0.0
        if: github.event_name != 'pull_request'
        with:
          tag: ${{ steps.prep.outputs.version }}

      - name: Inspect
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.prep.outputs.version }}

      - name: Dockerhub description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v5.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKER_IMAGE_NAME }}
          readme-filepath: DOCKERHUB.md

      - name: Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        if: github.event_name != 'pull_request'
        with:
          generate_release_notes: true
          tag_name: ${{ steps.prep.outputs.version }} 